#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication topoSet

runApplication refineMesh -overwrite

rm log.topoSet

runApplication topoSet

runApplication decomposePar -cellDist

runParallel simpleFoam

runApplication reconstructPar

touch case.foam

#------------------------------------------------------------------------------
