#!/bin/sh
cd "${0%/*}" || exit                                # Run from this directory
. ${WM_PROJECT_DIR:?}/bin/tools/RunFunctions        # Tutorial run functions
#------------------------------------------------------------------------------

restore0Dir

runApplication blockMesh

runApplication topoSet

runApplication refineMesh -overwrite

mv log.topoSet log.topoSet_init

runApplication topoSet

runApplication decomposePar -cellDist

runParallel $(getApplication)

runApplication reconstructParMesh

runApplication reconstructPar

touch case.foam

#------------------------------------------------------------------------------
