#!/bin/bash

# slurm script to run this case in Clemetina XXI supercomputer

#SBATCH --job-name=wtActuatorFOAM-abl
#SBATCH --nodes=1
#SBATCH --partition=batch
#SBATCH --exclusive
#SBATCH --time=1-00:00:00

# Load modules and OpenFOAM environment
module purge
module load gnu/13.2.0
module load openmpi5/5.0.3
module load metis/5.1.0
source /data/contrib/pci_68/openfoam/OpenFOAM-v2506_local/etc/bashrc

srun ./Allrun_parallel
